---
title: "R Notebook"
output: html_notebook
---

Workforce jobs by region and industry (seasonally adjusted) excel file using Standard Industrial Classigication (SIC) standards

• Jobs
• Hours




```{r}
UK_Labour_Productivity_Jobs_in_Regions_by_Industry %>%
    filter(year_month == max(year_month)) %>%
    group_by(industry) %>% 
    summarise(total_jobs = sum(jobs)) %>% 
    arrange(desc(total_jobs))

```

```{r}
scotland_jobs %>%
    filter(year_month == max(year_month)) %>%
    group_by(industry) %>% 
    summarise(total_jobs = sum(jobs)) %>% 
    arrange(desc(total_jobs))
```





```{r}
UK_regional_output_per_hour %>% 
    filter(year == max(year),
           subsector_letter == "all_industries")
```

```{r}
UK_regional_output_per_hour %>% 
    filter(year == max(year),
           industry != "all_industries") %>%
    group_by(region, industry) %>% 
    summarise(industry_output_per_hour = sum(output_per_hour)) %>% 
    arrange(industry_output_per_hour)
```

```{r}
UK_regional_output_per_job %>% 
    filter(year == max(year),
           industry != "all_industries") %>%
    group_by(region, industry) %>% 
    summarise(industry_output_per_job = sum(output_per_job)) %>% 
    arrange(industry_output_per_job)
```

