---
title: "R Notebook"
output: html_notebook
---

Data was donated by Deloitte and comes from the Equifax Ignite Direct data platform, which will host over 50 open data sources.

# Brief

• Data & Challenge Insight – the depth of your investigation into the data and the maturity of your understanding of how productivity can be improved.
• Insight Quality – the quality and level of detail expressed in your data insight including visualisations.
• Concept Feasibility – the viability of your solution/concept in the wider context of the market such as practicality, cost & impact. 

https://www.oecd.org/sdd/productivity-stats/40526851.pdf

## Initial comments
• Data is extensive and unwieldy
• Data comes in spreadsheets and is not formatted well and will require heavy cleaning

## Initial assessment
• Amount of data cleaning could be reduced by targeting attention to key areas of interest
• Keep in mind the accuracy of the data
• 

## Questions to answer
• Are there other, cleaner, sources of the same data
• How much of it is required to get started with initial exploration
• How much of it is required for indepth analysis
• Has the client oversimplified the problem in any way - e.g. part-employment, zero-hour contracts etc.
• What has been the effect of changing sector dominance in UK
• How about Scotland specifically
• What are the effects of inflation, technological progress and economic crises.

# Initial thoughts
• Careful planning might save some time
• Explanatory versus predictive models
• Is low productivity a natural course of events for developed countries?




# The productivity problem


## local business development and the wider economy are affected by productivity




## Over the past decade, productivity has slowed down globally


## UK lags behind some other developed economies



## “Productivity is commonly defined as a ratio between the output volume and the volume of inputs.

## Measures how efficiently production inputs are being used in an economy to produce a given level of output.

## Labour and capital inputs

## Identify and target industries with low productivity levels


## Example of initiatives within other nations to increase local productivity

# Main business question is generally: How can we improve productivity within Scotland and the UK overall?
 

## What factors can be improved to increase employee and/or business productivity across UK regions?



## Which industries are lagging behind in terms of productivity and how could they catch up?



## Can we predict overall UK productivity rates?






